### ISSUE TITLE
Using chillaxd on a macbook pro with osx10.10.5

### ISSUE THREAD

**Issue by rwerthman** [ylamgarchal/chillaxd#3]
Hello,

When I follow you directions using 'git clone' and 'sudo python setup.py install' I have problems getting 'chillaxd' to run.  First funning 'tox' doesn't work and secondly when I try just 'chillaxd' I get this error.  It seems something is wrong with pyzmq.  I tried a newer version of pyzmq but I then get an error 'pkg_resources.DistributionNotFound: pyzmq>=14.3.1,<14.4.0' from 'chillaxd'.

Bobs-MacBook-Pro:chillaxd Bob$ chillaxd
Traceback (most recent call last):
  File "/usr/local/bin/chillaxd", line 9, in <module>
    load_entry_point('chillaxd==0.1a2', 'console_scripts', 'chillaxd')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "build/bdist.macosx-10.10-intel/egg/chillaxd/chillax_server.py", line 18, in <module>
  File "build/bdist.macosx-10.10-intel/egg/chillaxd/raft/server.py", line 23, in <module>
  File "/Library/Python/2.7/site-packages/pyzmq-14.3.1-py2.7-macosx-10.6-intel.egg/zmq/**init**.py", line 49, in <module>
  File "/Library/Python/2.7/site-packages/pyzmq-14.3.1-py2.7-macosx-10.6-intel.egg/zmq/backend/**init**.py", line 41, in <module>
  File "/Library/Python/2.7/site-packages/pyzmq-14.3.1-py2.7-macosx-10.6-intel.egg/zmq/backend/**init**.py", line 29, in <module>
  File "/Library/Python/2.7/site-packages/pyzmq-14.3.1-py2.7-macosx-10.6-intel.egg/zmq/backend/select.py", line 26, in select_backend
  File "/Library/Python/2.7/site-packages/pyzmq-14.3.1-py2.7-macosx-10.6-intel.egg/zmq/backend/cython/**init**.py", line 6, in <module>
  File "/Library/Python/2.7/site-packages/pyzmq-14.3.1-py2.7-macosx-10.6-intel.egg/zmq/backend/cython/error.py", line 7, in <module>
  File "/Library/Python/2.7/site-packages/pyzmq-14.3.1-py2.7-macosx-10.6-intel.egg/zmq/backend/cython/error.py", line 6, in **bootstrap**
ImportError: dlopen(/Users/Bob/.python-eggs/pyzmq-14.3.1-py2.7-macosx-10.6-intel.egg-tmp/zmq/backend/cython/error.so, 2): Symbol not found: _zmq_errno
  Referenced from: /Users/Bob/.python-eggs/pyzmq-14.3.1-py2.7-macosx-10.6-intel.egg-tmp/zmq/backend/cython/error.so
  Expected in: flat namespace
 in /Users/Bob/.python-eggs/pyzmq-14.3.1-py2.7-macosx-10.6-intel.egg-tmp/zmq/backend/cython/error.so

Any ideas on how to fix this?

Thanks!

**Comment by joehakimrahme** [comment]
I'm also on OS X 10.10.5 and the instructions work for me.
- `tox` works without any issue. I'm using tox==1.7.2
-  `python setup.py install` in a freshly created virtualenv works as well. It installed pyzmq==14.7.0
- I get no error when I launch `chillaxd`

It does look like you're downloading the wrong version of pyzmq. Can you try installing 14.7.0? It should fit the requirements.txt

Alternatively, can you try launching this in a virtualenv?

**Comment by rwerthman** [comment]
Ok, thanks!  I'll give it a try.
